version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    groups:
      expo:
        patterns:
          - "expo"
          - "expo-*"
          - "@expo/*"
      react-native:
        patterns:
          - "react-native"
          - "react-native-*"
          - "@react-native/*"
          - "@react-native-*"
